version: '3'

services:
  ctfd:
    image: kcrong/demon-ctf
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
    volumes:
      - .data/CTFd/logs:/opt/CTFd/CTFd/logs
      - .data/CTFd/uploads:/opt/CTFd/CTFd/uploads
    depends_on:
      - db
    deploy:
      replicas: 3

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    deploy:
      replicas: 1
